# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "thunderbolt" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a431aa0-b6c1-4357-a791-ed137a21798c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/11A7-941B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/storage" =
    { device = "/dev/disk/by-uuid/466e4aeb-5fe2-4bd9-b7e1-b1e05e9cf1d7";
      fsType = "ext4";
    };

  fileSystems."/nas" =
    { device = "truenas.home:/mnt/main/files";
      fsType = "nfs4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8b985d69-12fc-499b-86ca-ce65e83763e7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
