vim.lsp.enable('rust_analyzer')
vim.lsp.enable('rustfmt')
vim.lsp.enable('nixd')
vim.lsp.enable('nixfmt')
vim.lsp.enable('stylua')
vim.lsp.enable('jdtls')
-- vim.lsp.enable('ccls')
vim.lsp.enable('clangd')
